### ISSUE TITLE
没反应，加了书签后，直播间卡住了，视频加载不出来

### ISSUE THREAD

**Issue by Qiufeng125** [lhfy1990/bilibiliTools#7]
![default](https://user-images.githubusercontent.com/38995766/39869755-52e21c66-5491-11e8-93a8-b090968caead.JPG)

**Comment by Qiufeng125** [comment]
不会用

**Comment by lhfy1990** [comment]
@Qiufeng125 使用方法是在打开直播间后点击书签，正确加载后应当弹出提示框。点击确定后左下角应当有一个浮动的bilibili图标，可以点击。直播间视频无法加载应当是网络问题，与本插件无关。
另外这星期发现小电视抽奖无法正常工作，正在修理中。

**Comment by lhfy1990** [comment]
@Qiufeng125 BiliBili修改了小电视通知关键词，已更新 #8 。同时更新使用说明 #9 。
